#!/bin/sh
set -eu

while read -r local_ref local_oid remote_ref remote_oid; do
  if [ "$remote_ref" = "refs/heads/main" ] &&
    [ "$local_oid" != "0000000000000000000000000000000000000000" ]; then
    pnpm check
    exit 0
  fi
done
