import type { UiLocale } from '@fuxian/shared-types';

const englishMessages = {
  A4: 'A4',
  '暂时无法重启安装，请稍后重试。': 'Could not restart the installer. Try again later.',
  '当前环境不支持软件更新。': 'Software updates are unavailable in this environment.',
  'PlantUML Server 验证失败。': 'PlantUML Server validation failed.',
  '请输入有效的 HTTP 或 HTTPS PlantUML Server 地址。':
    'Enter a valid HTTP or HTTPS PlantUML Server URL.',
  'PlantUML 源码为空或超过 500,000 个字符。':
    'PlantUML source is empty or exceeds 500,000 characters.',
  'PlantUML Server 返回的 SVG 超过 5 MB。': 'The PlantUML Server returned SVG larger than 5 MB.',
  'PlantUML Server 没有返回内容。': 'The PlantUML Server returned no content.',
  'PlantUML Server 返回 HTTP {status}。': 'The PlantUML Server returned HTTP {status}.',
  'PlantUML Server 没有返回有效的 SVG。': 'The PlantUML Server did not return valid SVG.',
  '定位 Markdown': 'Locate Markdown',
  '无法读取“{name}”。请确认文件仍然存在并可访问。':
    'Could not read “{name}”. Make sure the file still exists and is accessible.',
  '“{name}”不是 Markdown 文档。': '“{name}” is not a Markdown document.',
  '系统交给应用的文档暂时无法打开。':
    'The document provided by the system could not be opened right now.',
  '读取图片时发生错误。': 'An error occurred while reading the image.',
  '已有 PDF 正在导出。': 'A PDF export is already running.',
  'PDF 导出页面准备超时。': 'The PDF export page timed out while preparing.',
  'PDF 导出页面加载失败。': 'The PDF export page failed to load.',
  'PDF 导出进程意外退出。': 'The PDF export process exited unexpectedly.',
  'PDF 导出页面准备失败。': 'The PDF export page could not be prepared.',
  '纸张预览为 {expected} 页，但 PDF 分页为 {actual} 页。':
    'The paper preview has {expected} pages, but the PDF has {actual} pages.',
  '写入 PDF 超时。': 'Writing the PDF timed out.',
  'PlantUML 渲染请求无效。': 'The PlantUML rendering request is invalid.',
  '连接 PlantUML Server 超时。': 'Connecting to the PlantUML Server timed out.',
  '保存请求无效或文档不属于当前会话。':
    'The save request is invalid or the document is not part of the current session.',
  '另存请求无效。': 'The Save As request is invalid.',
  '目标文档在保存期间发生变化，请重新选择。':
    'The destination changed while saving. Choose it again.',
  '该文档不属于当前文档会话。': 'This document is not part of the current session.',
  知道了: 'OK',
  '在访达中右键示例文档，选择“显示简介”，在“打开方式”中选择“浮现”，再点击“全部更改”。系统确认后返回浮现。':
    'In Finder, right-click the sample document and choose Get Info. Under Open with, choose Fuxian, then click Change All. Return to Fuxian after macOS confirms the change.',
  '开发模式不会检测或修改系统文件关联。请安装正式版本后查看。':
    'Development mode does not detect or change system file associations. Check again in an installed build.',
  '开发模式不会打开或修改系统文件关联。':
    'Development mode does not open or change system file associations.',
  '已打开 Windows 默认应用设置。若系统未定位到浮现，请搜索 Fuxian，再确认 .md 与 .markdown 均选择浮现。':
    'Windows Default Apps is open. If Fuxian is not selected, search for Fuxian and choose it for both .md and .markdown.',
  浮现默认应用设置: 'Fuxian Default App Setup',
  '只能保存 Markdown 文档。': 'Only Markdown documents can be saved.',
  '源文档路径已发生变化，请重新打开文档。':
    'The source document path changed. Reopen the document.',
  '无法保存“{name}”。请检查文件权限后重试。':
    'Could not save “{name}”. Check file permissions and try again.',
  '无法将文档保存到“{name}”。请检查目标位置后重试。':
    'Could not save the document to “{name}”. Check the destination and try again.',
  摘要: 'Abstract',
  缺陷: 'Bug',
  注意: 'Caution',
  危险: 'Danger',
  示例: 'Example',
  失败: 'Failure',
  重要: 'Important',
  信息: 'Info',
  备注: 'Note',
  问题: 'Question',
  引用: 'Quote',
  成功: 'Success',
  提示: 'Tip',
  待办: 'Todo',
  警告: 'Warning',
  '图表服务没有返回有效的 SVG。': 'The diagram service did not return valid SVG.',
  '图表包含过多 SVG 元素。': 'The diagram contains too many SVG elements.',
  '图表所在文档尚未就绪。': 'The diagram document is not ready yet.',
  '当前环境无法安全处理 SVG。': 'SVG cannot be processed safely in this environment.',
  '图表没有通过 SVG 安全校验。': 'The diagram did not pass SVG security validation.',
  '渲染任务失败。': 'Rendering failed.',
  'PlantUML 渲染服务不可用。': 'The PlantUML rendering service is unavailable.',
  文档开头: 'Start of document',
  '文档开头 · 图表 {ordinal}': 'Start of document · Diagram {ordinal}',
  '{heading} · 图表 {ordinal}': '{heading} · Diagram {ordinal}',
  '{kind} 图表 {ordinal}，{heading}': '{kind} diagram {ordinal}, {heading}',
  图表操作: 'Diagram actions',
  全屏查看图表: 'View diagram full screen',
  '渲染任务占位已不存在。': 'The rendering placeholder no longer exists.',
  '渲染超时，请重试。': 'Rendering timed out. Try again.',
  '静态文档快照不执行渲染任务。': 'Static document snapshots do not run rendering tasks.',
  '完成文档快照不可用。': 'The finished-document snapshot is unavailable.',
  无法呈现信息图: 'Unable to display infographic',
  无法呈现图表: 'Unable to display diagram',
  无法呈现公式: 'Unable to display formula',
  无法加载图片: 'Unable to load image',
  '图片地址无效或使用了不安全的协议。': 'The image address is invalid or uses an unsafe protocol.',
  '图片路径超出了文档的授权范围。': 'The image path is outside the document’s authorized folder.',
  '不支持这种图片格式。': 'This image format is not supported.',
  '只允许访问文档目录内的相对图片。':
    'Only relative images inside the document folder are allowed.',
  '请确认图片存在且文件内容完整。': 'Make sure the image exists and the file is complete.',
  复制代码: 'Copy code',
  安装更新: 'install the update',
  '正在准备纸张...': 'Preparing paper...',
  '正在分页...': 'Paginating...',
  '正在更新分页...': 'Updating pages...',
  更新失败: 'Update failed',
  '新版本 Markdown 无法解析。': 'The new Markdown version could not be parsed.',
  '新版本无法完整呈现。': 'The new version could not be rendered completely.',
  '应用暂时无法重新读取源文档。': 'Fuxian cannot reread the source document right now.',
  '应用无法读取拖入的文档。请确认文件仍然存在。':
    'Fuxian could not read the dropped document. Make sure the file still exists.',
  进入编辑模式: 'Enter editing mode',
  进入阅读模式: 'Enter reading mode',
  '纸张分页失败。': 'Paper pagination failed.',
  重试文档更新: 'Retry document update',
  连续阅读: 'Continuous reading',
  外部修改冲突: 'External edit conflict',
  '无法保存当前文档会话。': 'Could not save the current document session.',
  '存在尚未保存的 Markdown 修改。': 'There are unsaved Markdown changes.',
  '切换正在查看的文档或重新查看最近文档。':
    'Switch between open documents or reopen recently viewed documents.',
  'A4 分页预览': 'A4 paged preview',
  'A4 纸张': 'A4 paper',
  English: 'English',
  'Markdown 源码编辑区': 'Markdown source editor',
  'Markdown 源码编辑器': 'Markdown source editor',
  'Markdown 默认应用': 'Default Markdown app',
  'Markdown 默认应用说明':
    'Checks .md and .markdown separately. Fuxian changes file associations only after your explicit action.',
  'PDF 分页文档': 'Paginated PDF document',
  'PDF 导出窗口意外关闭。': 'The PDF export window closed unexpectedly.',
  'PDF 导出进度': 'PDF export progress',
  'PDF 已导出': 'PDF exported',
  'Server 地址': 'Server URL',
  'PlantUML Server 设置说明':
    'The public service is used by default. A URL is saved only after validation, then open PlantUML diagrams are redrawn immediately.',
  'PlantUML 源码发送说明':
    'PlantUML source is sent to the configured service. Do not include sensitive content that should remain on this device.',
  '.md 与 .markdown 均由浮现默认打开。': 'Fuxian opens both .md and .markdown files by default.',
  '.md 与 .markdown 当前均由其他应用默认打开。':
    'Another application currently opens both .md and .markdown files by default.',
  '.md：{md}；.markdown：{markdown}。': '.md: {md}; .markdown: {markdown}.',
  '“{name}”已在外部修改': '“{name}” was modified externally',
  '“{name}”的内容暂时无法呈现。': '“{name}” cannot be displayed right now.',
  '{kind} 图表源码': '{kind} diagram source',
  '{kind} 源码': '{kind} source',
  '{name} · {count} 个标题': '{name} · {count} headings',
  '{count} 页': '{count} pages',
  '{action}前需要处理尚未保存的 Markdown 源码。恢复草稿不能代替正式保存。':
    'Before you {action}, unsaved Markdown source must be handled. A recovery draft does not replace a saved document.',
  一般用于打印与交付: 'Best for printing and delivery',
  上一个匹配项: 'Previous match',
  下一个匹配项: 'Next match',
  下载更新: 'Download update',
  不保存: 'Don’t Save',
  其他应用: 'Another app',
  中文: 'Chinese',
  代码高亮主题: 'Code highlighting theme',
  代码高亮主题说明:
    'Independent of the app appearance. Switch themes to preview representative code on the right.',
  保存: 'Save',
  保留本地修改: 'Keep Local Changes',
  '保存 Markdown': 'Save Markdown',
  保存失败: 'Save failed',
  '保存对“{name}”的修改？': 'Save changes to “{name}”?',
  全部显示: 'Show All',
  '关于 Fuxian': 'About Fuxian',
  关于与更新: 'About',
  关于浮现: 'About Fuxian',
  关闭: 'Close',
  '关闭“{name}”': 'Close “{name}”',
  关闭图表源码: 'Close diagram source',
  关闭大纲图: 'Close outline map',
  关闭文档: 'close the document',
  关闭窗口: 'close the window',
  关闭查找: 'Close find',
  关闭浮现: 'Quit Fuxian',
  切换全屏: 'Toggle Full Screen',
  切换开发者工具: 'Toggle Developer Tools',
  切换文档: 'switch documents',
  剪切: 'Cut',
  '前往 GitHub Release': 'Open GitHub Release',
  前置全部窗口: 'Bring All to Front',
  加载失败: 'Loading failed',
  正在准备文档: 'Preparing document',
  '正在准备源码编辑器...': 'Preparing source editor...',
  正在准备纸张预览: 'Preparing paper preview',
  '正在保存...': 'Saving...',
  '正在写入 PDF': 'Writing PDF',
  '正在打开...': 'Opening...',
  '正在恢复上次会话...': 'Restoring your previous session...',
  正在更新: 'Updating',
  '正在更新...': 'Updating...',
  '正在检查更新...': 'Checking for updates...',
  '正在检查系统设置...': 'Checking system settings...',
  正在渲染内容: 'Rendering content',
  正在生成文章大纲图: 'Generating article outline map',
  正在验证: 'Validating',
  '正在下载 {version}': 'Downloading {version}',
  '正在重启并安装更新...': 'Restarting to install the update...',
  内容层次: 'Content hierarchy',
  内容已复制: 'Content copied',
  实际大小: 'Actual Size',
  '宽度：{width}px': 'Width: {width}px',
  '将浮现设为 Markdown 默认应用': 'Set Fuxian as the default Markdown app',
  已保存: 'Saved',
  '已取消下载，可以稍后重新检查。': 'The download was canceled. You can check again later.',
  已是默认应用: 'Default app',
  '已更新 · {time}': 'Updated · {time}',
  '已恢复草稿 · 未保存': 'Recovered draft · Unsaved',
  已验证并保存: 'Validated and saved',
  已复制: 'Copied',
  '已将浮现设为 .md 与 .markdown 的默认应用。':
    'Fuxian is now the default app for .md and .markdown files.',
  '展开“{heading}”下的深层标题': 'Expand deeper headings under “{heading}”',
  展开大纲: 'Show outline',
  展开导出进度: 'Expand export progress',
  展开深层标题: 'Expand deeper headings',
  展开文档会话: 'Show document session',
  帮助: 'Help',
  '应用暂时无法访问文件。请重试或重新打开窗口。':
    'Fuxian cannot access the file right now. Try again or reopen the window.',
  '应用暂时无法访问该文档。': 'Fuxian cannot access this document right now.',
  '应用暂时无法保存文档，请重试。': 'Fuxian cannot save the document right now. Try again.',
  '应用暂时无法启动 PDF 导出。': 'Fuxian cannot start PDF export right now.',
  '应用暂时无法另存文档，请重试。':
    'Fuxian cannot save a copy of the document right now. Try again.',
  '应用暂时无法打开所选文档。': 'Fuxian cannot open the selected document right now.',
  当前已是最新版本: 'You’re up to date',
  当前文章的大纲思维导图: 'Mind map of the current article outline',
  当前文档没有标题: 'This document has no headings',
  '当前文档不属于受信任的文档会话。':
    'The current document does not belong to the trusted document session.',
  当前环境不检查更新: 'Updates are unavailable in this environment',
  '当前环境无法读取文件关联。': 'File associations cannot be read in this environment.',
  '当前版本 {version}': 'Current version {version}',
  '当前系统暂不支持检测 Markdown 默认应用。':
    'This system does not support detecting the default Markdown app.',
  '当前系统暂不支持此设置入口。': 'This setting is not supported on the current system.',
  恢复默认: 'Restore Default',
  '打开 Markdown': 'Open Markdown',
  '打开 Markdown…': 'Open Markdown…',
  打开其他文档: 'Open another document',
  打开文档: 'Open document',
  打开文档会话: 'Open document session',
  打开方式: 'Open With',
  强制重新加载: 'Force Reload',
  当前文章结构: 'Current article structure',
  '折叠“{heading}”下的深层标题': 'Collapse deeper headings under “{heading}”',
  折叠大纲: 'Hide outline',
  折叠大纲图: 'Collapse outline map',
  折叠导出进度: 'Collapse export progress',
  折叠深层标题: 'Collapse deeper headings',
  拖放手柄: 'Drag handle',
  拷贝: 'Copy',
  按住并拖动以调整文档宽度: 'Drag to adjust the document width',
  接收外部更新: 'Receive external updates',
  搜索: 'Search',
  撤销: 'Undo',
  放大: 'Zoom In',
  放大图表: 'Zoom in on diagram',
  放大文章大纲图: 'Zoom in on outline map',
  文件: 'File',
  '文件名必须使用 .md 或 .markdown 扩展名。':
    'The file name must use the .md or .markdown extension.',
  文档: 'Document',
  文档会话: 'Document session',
  文档不可用: 'Document unavailable',
  文档宽度: 'Document width',
  文档宽度模式: 'Document width mode',
  文档宽度设置说明:
    'Adjusts the entire white document surface. Body text, tables, code, formulas, images, and diagrams share its inner width.',
  文档宽度弹窗说明:
    'Adjusts the entire white document surface. Body text, tables, code, and diagrams share its inner width.',
  文档显示模式: 'Page mode',
  文档更新失败: 'Document update failed',
  文档标题: 'Document headings',
  文章大纲图: 'Article outline map',
  '新版本 {version} 可用': 'Version {version} is available',
  无界: 'Continuous',
  无界阅读: 'Continuous reading',
  '无法准备 PDF 文档。': 'Could not prepare the PDF document.',
  '无法准备纸张预览。': 'Could not prepare the paper preview.',
  无法复制: 'Could not copy',
  无法打开文档: 'Unable to open document',
  '无法打开 GitHub Release，请稍后重试。':
    'Could not open the GitHub Release. Please try again later.',
  '无法恢复上次文档会话。你仍可以重新打开文档。':
    'Your previous document session could not be restored. You can reopen documents.',
  无法检测: 'Unavailable',
  '无法生成 PDF。': 'Could not generate the PDF.',
  '无法生成文章大纲图。': 'Could not generate the article outline map.',
  无法生成文章大纲图: 'Could not generate the article outline map',
  '无法下载更新，请检查网络后重试。':
    'Could not download the update. Check your connection and try again.',
  '无法检查更新，请检查网络后重试。':
    'Could not check for updates. Check your connection and try again.',
  '无法识别拖入的文档。': 'The dropped document could not be recognized.',
  '无法重启安装，请稍后重试。': 'Could not restart the installer. Please try again later.',
  显示大纲: 'Show outline',
  显示简介: 'Get Info',
  '暂时无法完成更新。': 'The update could not be completed right now.',
  '暂时无法打开系统默认应用设置。': 'The system default-app settings cannot be opened right now.',
  '暂时无法验证 PlantUML Server。': 'The PlantUML Server could not be validated.',
  最小化: 'Minimize',
  最近查看: 'Recently viewed',
  有可用更新: 'Update available',
  有新内容: 'New content',
  更新下载进度: 'Update download progress',
  更新内容: 'What’s new',
  更新已准备好: 'Update ready',
  未保存: 'Unsaved',
  '未写入 PDF 文件。': 'No PDF file was written.',
  来源发送范围: 'Source sharing',
  查看大纲图: 'View outline map',
  '查看并复制当前 Mermaid 或 PlantUML 图表源码。':
    'View and copy the current Mermaid or PlantUML diagram source.',
  '查看当前版本，并在你准备好时下载和安装更新。':
    'View the current version and download an update when you are ready.',
  '查看当前版本，有新版本时前往 GitHub Release 下载。':
    'View the current version and download new releases from GitHub.',
  查看图表源码: 'View diagram source',
  查找: 'Find',
  检查更新: 'Check for Updates',
  '检查更新…': 'Check for Updates…',
  正在查看: 'Open documents',
  正文: 'Body',
  正文字体: 'Body font',
  正文字号: 'Body size',
  正文行高: 'Line height',
  '正式安装的 Windows 和 macOS 版本支持软件更新。':
    'Installed Windows and macOS builds support software updates.',
  浅色: 'Light',
  'GitHub 浅色': 'GitHub Light',
  'GitHub 深色': 'GitHub Dark',
  浮现: 'Fuxian',
  '浮现保留了本地编辑内容和最新磁盘版本。请选择要继续使用的版本，任何内容都不会被静默覆盖。':
    'Fuxian kept both your local edits and the latest version on disk. Choose which version to continue with; nothing will be overwritten silently.',
  浮现浅色: 'Fuxian Light',
  浮现深色: 'Fuxian Dark',
  '测试适配器已模拟打开系统默认应用设置。':
    'The test adapter simulated opening the system default-app settings.',
  '测试适配器模拟当前环境无法检测。': 'The test adapter reports that detection is unavailable.',
  深色: 'Dark',
  添加文档: 'Add document',
  '源文件已被移动或删除。未保存的源码仍保留在当前编辑器和恢复草稿中。':
    'The source file was moved or deleted. Unsaved source remains in the editor and recovery draft.',
  源码: 'Source',
  源码发送范围: 'Source sharing',
  '源码已保存，但无法生成阅读内容。':
    'The source was saved, but the finished document could not be generated.',
  '源码已保存，但无法生成阅读内容：{detail}':
    'The source was saved, but the finished document could not be generated: {detail}',
  '版本 {version}': 'Version {version}',
  用户界面语言: 'Interface language',
  '界面语言会立即应用到浮现的所有窗口。':
    'The interface language applies immediately to every Fuxian window.',
  纸张: 'Paper',
  纸张预览: 'Paper preview',
  纸张预览页面: 'Paper preview pages',
  编辑: 'Edit',
  缩小: 'Zoom Out',
  缩小图表: 'Zoom out of diagram',
  缩小文章大纲图: 'Zoom out of outline map',
  自定义: 'Custom',
  自适应: 'Adaptive',
  自定义文档宽度: 'Custom document width',
  自动适应窗口: 'Fit to window',
  菜单: 'Menu',
  衬线: 'Serif',
  设置: 'Settings',
  '设置…': 'Settings…',
  浮现设置: 'Fuxian Settings',
  设置分区: 'Settings sections',
  '设置，有可用更新': 'Settings, update available',
  '该文档的内容暂时无法呈现。': 'This document cannot be displayed right now.',
  详情: 'Details',
  '请先打开一个 Markdown 文档。': 'Open a Markdown document first.',
  请选择: 'Select',
  跟随系统: 'Follow System',
  软件更新失败: 'Software update failed',
  输入内容以查找: 'Enter text to find',
  '退出 Fuxian': 'Quit Fuxian',
  退出浮现: 'Quit Fuxian',
  '连接验证成功，地址已保存。': 'Connection verified. The URL was saved.',
  重新加载: 'Reload',
  重做: 'Redo',
  重新检查: 'Check Again',
  重启并更新: 'Restart and Update',
  '重启浮现即可安装 {version}。': 'Restart Fuxian to install {version}.',
  重试: 'Retry',
  '重试“{name}”': 'Retry “{name}”',
  '定位“{name}”': 'Locate “{name}”',
  删除: 'Delete',
  '移除“{name}”': 'Remove “{name}”',
  窗口: 'Window',
  立即更新: 'Update Now',
  稍后: 'Later',
  '管理浮现与操作系统的集成。': 'Manage how Fuxian integrates with your operating system.',
  '系统未能直接完成设置，已在访达中显示示例文档，可通过“显示简介”继续设置。':
    'The system could not complete the change directly. A sample document is shown in Finder so you can continue from Get Info.',
  '系统没有返回可靠的 Markdown 文件关联状态。':
    'The system did not return a reliable Markdown file-association status.',
  统一宽度下显示正文与图表: 'Shows text and diagrams at one unified width',
  继续阅读: 'Continue reading',
  继续编辑: 'Continue editing',
  '继续操作前需要处理尚未保存的 Markdown 源码。恢复草稿不能代替正式保存。':
    'Unsaved Markdown source must be handled before continuing. A recovery draft does not replace a saved document.',
  复制: 'Copy',
  '复制 SVG': 'Copy SVG',
  复制失败: 'Copy failed',
  复制源码: 'Copy source',
  视图: 'View',
  语言: 'Language',
  调整大纲宽度: 'Resize outline',
  调整文档会话宽度: 'Resize document session',
  贴入并匹配样式: 'Paste and Match Style',
  '选择应用和完成文档的明暗外观。':
    'Choose the light or dark appearance for the app and finished documents.',
  '选择的文档暂时无法呈现。请检查文件内容后重试。':
    'The selected document cannot be displayed. Check its contents and try again.',
  采用磁盘版本: 'Use Version on Disk',
  部分关联: 'Partially associated',
  部分文档暂时不可用: 'Some documents are unavailable',
  '配置用于生成 PlantUML SVG 的公共、本地或私有服务。':
    'Configure a public, local, or private service for generating PlantUML SVG.',
  错误: 'Error',
  页内查找: 'Find in document',
  项目主页: 'Project Homepage',
  颜色模式: 'Color mode',
  高级设置: 'Advanced settings',
  图表全屏画布: 'Full-screen diagram canvas',
  图表源码: 'Diagram source',
  图表缩放比例: 'Diagram zoom level',
  大纲: 'Outline',
  大纲图: 'Outline map',
  完成文档示例: 'Finished document sample',
  完成文档预览: 'Finished document preview',
  完成文档阅读区: 'Finished document reading area',
  验证并保存: 'Validate and Save',
  隐藏其他窗口: 'Hide Others',
  隐藏大纲: 'Hide outline',
  隐藏浮现: 'Hide Fuxian',
  默认应用: 'Default app',
  '默认使用公共服务。地址验证通过后才会保存，并立即重绘已打开文档中的 PlantUML 图表。':
    'The public service is used by default. A URL is saved only after validation, then open PlantUML diagrams are redrawn immediately.',
  默认语言: 'Default language',
  取消: 'Cancel',
  取消下载: 'Cancel Download',
  另存为: 'Save As',
  '另存 Markdown': 'Save Markdown As',
  '可在左侧对文档执行重试、重新定位或移除。':
    'Use the controls on the left to retry, relocate, or remove a document.',
  '可以缩放、平移、适应窗口并复制当前图表。': 'Zoom, pan, fit, and copy the current diagram.',
  同步内容: 'Sync content',
  向后: 'Forward',
  向前: 'Back',
  无衬线: 'Sans Serif',
  '设为 Markdown 默认应用': 'Set as Default Markdown App',
  不是默认应用: 'Not the default app',
  全屏图表: 'Full-screen diagram',
  全屏图表操作说明:
    'Zoom, pan, fit, and copy the current diagram. Focus the canvas to pan with arrow keys, zoom with plus or minus, and press zero to reset.',
  返回: 'Back',
  返回文档: 'Back to document',
  定位到图表: 'Locate diagram',
  返回阅读模式: 'return to reading mode',
  适应文章大纲图窗口: 'Fit outline map to window',
  适应窗口: 'Fit to Window',
  通用: 'General',
  外观: 'Appearance',
  '让内容精彩浮现，让 Markdown 值得阅读。':
    'Let great content surface and make Markdown worth reading.',
  阅读: 'Read',
  阅读样式: 'Reading style',
  阅读宽度: 'Reading width',
  阅读模式: 'Reading mode',
  最近: 'Recent',
  刷新状态: 'Refresh Status',
  重新定位: 'Relocate',
  重新定位或移除: 'Relocate or remove',
  '设置全局文档宽度与正文排版。': 'Set the global document width and body typography.',
  更改会自动保存并应用到所有文档: 'Changes are saved automatically and applied to every document',
  '正在显示上一版本。{detail}': 'Showing the previous version. {detail}',
  松开以打开文档: 'Drop to open documents',
  或直接拖入文件: 'or drag files here',
  '浏览并跳转到当前文档中的标题。': 'Browse and navigate to headings in the current document.',
  收起文档会话: 'Collapse document session',
  实时预览: 'Live preview',
  '查看正在查看的文档或重新查看最近文档。':
    'Switch between open documents or reopen recently viewed documents.',
  显示完成文档: 'Show finished document',
  准备完成文档: 'Prepare finished document',
  '导出 PDF': 'Export PDF',
  导出失败: 'Export failed',
  导出已取消: 'Export canceled',
  '没有可打开的 Markdown 文档。': 'No Markdown documents could be opened.',
  浏览文件: 'Browse Files',
  删除当前文档: 'Remove current document',
  退出: 'Quit',
  粘贴: 'Paste',
  粘贴并匹配样式: 'Paste and Match Style',
  纸张预览暂时不可用: 'Paper preview is temporarily unavailable',
  '正在保留上一版纸张预览。{detail}': 'Keeping the previous paper preview. {detail}',
  全选: 'Select All',
  缩放: 'Zoom',
  重新打开窗口: 'Reopen Window',
  服务: 'Services',
} as const;

export type MessageKey = keyof typeof englishMessages;
export type MessageValues = Readonly<Record<string, number | string>>;
export type Translator = (key: MessageKey, values?: MessageValues) => string;

const chineseMessages: Partial<Record<MessageKey, string>> = {
  'Markdown 默认应用说明': '分别检查 .md 和 .markdown。仅在你明确操作后，浮现才会更改文件关联。',
  'PlantUML Server 设置说明':
    '默认使用公共服务。地址验证通过后才会保存，并立即重绘已打开文档中的 PlantUML 图表。',
  'PlantUML 源码发送说明':
    'PlantUML 源码会发送到上方配置的服务。包含敏感信息时，请改用可信的本地或私有服务。',
  代码高亮主题说明: '代码主题独立于应用外观。切换主题时，可在右侧预览典型代码。',
  文档宽度设置说明: '调整整个白色文档区域。正文、表格、代码、公式、图片和图表共享其内部宽度。',
  文档宽度弹窗说明: '调整整个白色文档区域。正文、表格、代码和图表共享其内部宽度。',
  全屏图表操作说明:
    '可缩放、平移、适应窗口并复制当前图表。聚焦画布后，可用方向键平移、加减号缩放，按 0 重置。',
};

const interpolate = (template: string, values?: MessageValues): string =>
  template.replaceAll(/\{([a-zA-Z][a-zA-Z\d]*)\}/gu, (placeholder, name: string) =>
    values?.[name] === undefined ? placeholder : String(values[name]),
  );

export const translate = (locale: UiLocale, key: MessageKey, values?: MessageValues): string =>
  interpolate(locale === 'zh-CN' ? (chineseMessages[key] ?? key) : englishMessages[key], values);

export const createTranslator =
  (locale: UiLocale): Translator =>
  (key, values) =>
    translate(locale, key, values);

export const productName = (locale: UiLocale): string => translate(locale, '浮现');
